### ISSUE TITLE
Specification Versioning should only refer to the section in Core

### ISSUE THREAD

**Issue by jamsden** [oasis-tcs/oslc-domains#3]
The section "Specification Versioning" should only have this content:
<p>This specification follows the specification version guidelines given in [OSLCCore3].</p>

It, and similar sections should not copy the text from the 2.0 specifications for anything that can be referenced from Core should not be duplicated to ensure consistency.

**Comment by ndjc** [comment]
Agreed (commenting partly to verify my write access to these issues!)
