### ISSUE TITLE
Making the 2.0 Domain Specifications based on OSLC Core 3.0, creates a compatibility problems, related to RDF representation formats.?

### ISSUE THREAD

**Issue by jadelkhoury** [oasis-tcs/oslc-domains#5]
(This issue applies for all Domain Specifications, but examplified here for the RM specs.)
 
OSLC Core 3.0, states that OSLC Services MUST provide and accept text/turtle
http://docs.oasis-open.org/oslc-core/oslc-core/v3.0/cs01/part1-overview/oslc-core-v3.0-cs01-part1-overview.html#resourceRepresentations 

But, the RM 2.0 DomainSpecs only requires MUST for RDF/XML representations.

Stating that RM 2.0 specification is based on OSLCCore3.0 creates a backward compatibility issues for RM2.0. Existing RM 2.0 implementations have not necessarily supported turtle.

A related issue is raised in OSLC Core under See https://issues.oasis-open.org/browse/OSLCCORE-142, suggesting the removed of requirements on RDF representation formats from Core.

**Suggestion1** (by Nicholas Crossley): For version numbering, we can't call it 2.0, because there are some differences. I thought we had agreed on 2.1 or 2.0.1 or something?

**Suggestion2**: If we are to follow Core's proposal to not require representation formats,  we should also then change the following (section 2.4 in the [RM] specs) from MUST to SHOULD?
RM Servers MUST support RDF/XML representations  ...
RM Servers MUST support XML representations ....

**Comment by jadelkhoury** [comment]
@jamsden

**Comment by jamsden** [comment]
Jad, can we resolve this?

**Comment by jadelkhoury** [comment]
I assumed we have already resolved this issue. I recall updating the RM specs to a formulation we were happy with.
But now I see though that the referenced issue in Core (https://issues.oasis-open.org/browse/OSLCCORE-142) is still open.
