### ISSUE TITLE
AM 3.0 draft of open-service

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/oslc-domains#6]
http://open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Specification-Version-3.0/

**Comment by jamsden** [comment]
I discussed this with Jim Conallen to see what should be done with this content. This draft version was never completed and was abandoned. It has a few errata from AM 2.0 that I included in 2.1, but removed LinkType and proposed a number of new classes that were decided to be IBM Design Manager specific. At this point there seems to be little interest in extending the OSLC AM spec, so we should base 2.1 on the 2.0 spec.
